fix(details): fix semantic structure of key-value pairs
fgpv-vpgf/fgpv-vpgf pull request #3933
Opened 2021-06-09 19:42 UTC by RyanCoulsonCA

Closes #3914 

Changes the HTML structure of key-value pairs in the details panel to use `<dl>`, `<dt>`, and `<dd>` tags. Additionally, the feature title is surrounded by `<h4>` tags.

A demo link can be found [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3914/samples/index-samples.html).

2021-06-09 20:00 UTC, james-rae approved these changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-09 20:21 UTC, milespetrov requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: all files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[packages/ramp-core/src/content/styles/modules/_lists.scss, line 68 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933#-MbmQmC--xp5b4z8xNMk:-MbmQmC--xp5b4z8xNMl:blc7xs7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42443a652f73cc1f6608b178dc34eeec7be364b8/packages/ramp-core/src/content/styles/modules/_lists.scss#L68)):*
> ```SCSS
>         @extend %base-list;
> 
>         > li, div {
> ```

Is the `li` still needed here? 
___
*[packages/ramp-core/src/content/styles/modules/_lists.scss, line 73 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933#-MbmOEN450wUTGhjQY-8:-MbmOEN450wUTGhjQY-9:blc7xs7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42443a652f73cc1f6608b178dc34eeec7be364b8/packages/ramp-core/src/content/styles/modules/_lists.scss#L73)):*
> ```SCSS
>         }
> 
>         > li, div:nth-child(even) {
> ```

Is the `li` still needed here? 


<!-- Sent from Reviewable.io -->

2021-06-10 13:08 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @james-rae and @milespetrov)

___
*[packages/ramp-core/src/content/styles/modules/_lists.scss, line 68 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933#-MbmQmC--xp5b4z8xNMk:-Mbq-yfICn1K1u_XQ_sb:b-fjz7h0) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42443a652f73cc1f6608b178dc34eeec7be364b8/packages/ramp-core/src/content/styles/modules/_lists.scss#L68)):*
<details><summary><i>Previously, milespetrov (Miles Petrov) wrote…</i></summary><blockquote>

Is the `li` still needed here? 
</blockquote></details>

Nope, doesn't look like it. I've removed it now.
___
*[packages/ramp-core/src/content/styles/modules/_lists.scss, line 73 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933#-MbmOEN450wUTGhjQY-8:-Mbq03xi8MsSoqG5pdgd:bss4a2b) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/42443a652f73cc1f6608b178dc34eeec7be364b8/packages/ramp-core/src/content/styles/modules/_lists.scss#L73)):*
<details><summary><i>Previously, milespetrov (Miles Petrov) wrote…</i></summary><blockquote>

Is the `li` still needed here? 
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2021-06-10 13:12 UTC, JahidAhmed approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: all files reviewed, 2 unresolved discussions (waiting on @milespetrov)



<!-- Sent from Reviewable.io -->

2021-06-10 13:14 UTC, yileifeng approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: all files reviewed, 2 unresolved discussions (waiting on @milespetrov)



<!-- Sent from Reviewable.io -->

2021-06-10 13:15 UTC, milespetrov approved these changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-10 14:57 UTC, sharvenp approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-10 17:21 UTC, james-rae approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-10 20:05 UTC, merged