feat(enhancedTable): add a toggle all button for column visibility
fgpv-vpgf/fgpv-vpgf pull request #3936
Opened 2021-06-11 13:32 UTC by RyanCoulsonCA

Closes #3821 

This PR adds a new `hide all` button to the `Hide columns` panel in the table.

If all columns are visible, clicking this button will hide all of the columns. If some columns are hidden, then clicking this button will make the hidden columns visible.

You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3821/samples/index-samples.html).

2021-06-11 13:55 UTC, spencerwahl requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[packages/ramp-plugin-enhanced-table/src/templates.ts, line 68 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-MbvLFnD5_QaMGpSjof5:-MbvLFnD5_QaMGpSjof6:b4lwxas) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f69a905829b57c62d39441dea103308908dadd46/packages/ramp-plugin-enhanced-table/src/templates.ts#L68)):*
> ```XML
>                 <md-button ng-click="ctrl.toggleColumn(col)" aria-label="{{ col.title }}" md-prevent-menu-close="md-prevent-menu-close">
>                     <span style='flex-basis: auto; overflow-wrap:normal;'>{{col.title}}</span>
>                     <md-icon md-svg-icon="action:done" ng-if="col.visibility"></md-icon>
> ```

Is it feasible to have one of these for the `All` button to indicate what it'll do on the next click (checkmark means all columns are visible so itll turn them off).


<!-- Sent from Reviewable.io -->

2021-06-11 14:32 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[packages/ramp-plugin-enhanced-table/src/templates.ts, line 68 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-MbvLFnD5_QaMGpSjof5:-MbvT9OABAwGQEjl8gB4:b-b502ns) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/f69a905829b57c62d39441dea103308908dadd46/packages/ramp-plugin-enhanced-table/src/templates.ts#L68)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

Is it feasible to have one of these for the `All` button to indicate what it'll do on the next click (checkmark means all columns are visible so itll turn them off).
</blockquote></details>

Yup, this should happen now.


<!-- Sent from Reviewable.io -->

2021-06-11 14:41 UTC, spencerwahl reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)



<!-- Sent from Reviewable.io -->

2021-06-11 14:41 UTC, spencerwahl approved these changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-11 14:52 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[packages/ramp-plugin-enhanced-table/src/index.ts, line 412 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-MbvXb_A2hZ8f8oBgYd7:-MbvXb_A2hZ8f8oBgYd8:b-8asi0w) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/634e6faa750f599f8b2b2dd695e6241c02c8dec9/packages/ramp-plugin-enhanced-table/src/index.ts#L412)):*
> ```XML
>             },
>             hideColumns: 'Hide columns',
>             hideAllColumns: 'All',
> ```

Since the behavior now with the checkmark indicates all columns are visible, maybe a more fitting name for the button would be `Show All`. Same goes for this variable name.


<!-- Sent from Reviewable.io -->

2021-06-11 14:56 UTC, spencerwahl commented
___
*[packages/ramp-plugin-enhanced-table/src/index.ts, line 412 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-MbvXb_A2hZ8f8oBgYd7:-MbvZWmo8gZcdOZBjYob:b-v7xv5i) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/634e6faa750f599f8b2b2dd695e6241c02c8dec9/packages/ramp-plugin-enhanced-table/src/index.ts#L412)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Since the behavior now with the checkmark indicates all columns are visible, maybe a more fitting name for the button would be `Show All`. Same goes for this variable name.
</blockquote></details>

I actually think `All` makes more sense with the checkmark, the show/hide is implied with all the other columns as well


<!-- Sent from Reviewable.io -->

2021-06-11 14:56 UTC, spencerwahl commented
___
*[packages/ramp-plugin-enhanced-table/src/index.ts, line 412 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-MbvXb_A2hZ8f8oBgYd7:-MbvZnc1EExfidlicG4l:b-geqvda) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/634e6faa750f599f8b2b2dd695e6241c02c8dec9/packages/ramp-plugin-enhanced-table/src/index.ts#L412)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

I actually think `All` makes more sense with the checkmark, the show/hide is implied with all the other columns as well
</blockquote></details>

Not a strong opinion on this though


<!-- Sent from Reviewable.io -->

2021-06-11 15:54 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[packages/ramp-plugin-enhanced-table/src/index.ts, line 412 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-MbvXb_A2hZ8f8oBgYd7:-MbvlRd8DZs9kfqllMY2:b-n9vtgx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/634e6faa750f599f8b2b2dd695e6241c02c8dec9/packages/ramp-plugin-enhanced-table/src/index.ts#L412)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

Not a strong opinion on this though
</blockquote></details>

I don't have much of a preference between the two, if anyone has a stronger opinion on it feel free to post it here.


<!-- Sent from Reviewable.io -->

2021-06-11 15:55 UTC, yileifeng reviewed
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-14 13:01 UTC, yileifeng approved these changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-14 13:13 UTC, sharvenp approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-14 17:37 UTC, james-rae requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[packages/ramp-plugin-enhanced-table/src/panel-manager.ts, line 849 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-McAa4q40hNtzSZGrTtm:-McAa4q40hNtzSZGrTtn:b-h4etap) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/634e6faa750f599f8b2b2dd695e6241c02c8dec9/packages/ramp-plugin-enhanced-table/src/panel-manager.ts#L849)):*
> ```XML
>                 // If any columns are not visible, then clicking the button should turn them on. If all columns are
>                 // visible, then clicking the button should turn them all off.
>                 this.columnVisibilities.filter((col) => col.visibility == !this.allColumnsVisible()).forEach((col) => {
> ```

put the value of ` !this.allColumnsVisible()` into a local var, then we won't be running `.some()` once for every column. Also, `===` for the big flex.


<!-- Sent from Reviewable.io -->

2021-06-14 17:48 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @james-rae, @sharvenp, @spencerwahl, and @yileifeng)

___
*[packages/ramp-plugin-enhanced-table/src/panel-manager.ts, line 849 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936#-McAa4q40hNtzSZGrTtm:-McAbncY9l2b0F9Hj0Pn:b-uazgvr) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/634e6faa750f599f8b2b2dd695e6241c02c8dec9/packages/ramp-plugin-enhanced-table/src/panel-manager.ts#L849)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

put the value of ` !this.allColumnsVisible()` into a local var, then we won't be running `.some()` once for every column. Also, `===` for the big flex.
</blockquote></details>

Fixed. I always seem to miss that sneaky extra `=`.


<!-- Sent from Reviewable.io -->

2021-06-14 18:32 UTC, james-rae approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-14 18:34 UTC, yileifeng approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-14 19:52 UTC, elsa-huang approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-15 12:54 UTC, milespetrov approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-15 15:46 UTC, james-rae approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-15 15:47 UTC, merged