WCAG: add roles and aria labels to sidenav buttons and modal
fgpv-vpgf/fgpv-vpgf pull request #3939
Opened 2021-06-14 13:32 UTC by yileifeng

Closes #3913 and #3920 

Adds the required dialog roles + aria properties for the sidenav as a modal and `aria-labels` for each of the buttons on the sidenav (all buttons were missing labels). 

[Demo page](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3920-3913-WCAG-roles-labels/samples/index-samples.html)

2021-06-14 13:49 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-14 16:08 UTC, spencerwahl requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[packages/ramp-core/src/app/ui/sidenav/sidenav.html, line 7 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939#-McAGiqH5mmAm-JZjI3F:-McAGiqH5mmAm-JZjI3G:b-x3lxam) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a78b4585a638cf87d25b6d199c82790c967d3305/packages/ramp-core/src/app/ui/sidenav/sidenav.html#L7)):*
> ```HTML
>     role="dialog"
>     aria-modal="true"
>     aria-labelledby="app-logotitle"
> ```

I think we should add the label directly, the ID on the header below will clash if there is more than one ramp instance.


<!-- Sent from Reviewable.io -->

2021-06-14 17:13 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-14 17:15 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[packages/ramp-core/src/app/ui/sidenav/sidenav.html, line 7 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939#-McAGiqH5mmAm-JZjI3F:-McAWHxyBqQtVJZH0duc:b499q7j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/a78b4585a638cf87d25b6d199c82790c967d3305/packages/ramp-core/src/app/ui/sidenav/sidenav.html#L7)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

I think we should add the label directly, the ID on the header below will clash if there is more than one ramp instance.
</blockquote></details>

Changed


<!-- Sent from Reviewable.io -->

2021-06-14 17:18 UTC, spencerwahl approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-14 18:15 UTC, james-rae approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-15 12:49 UTC, sharvenp approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-15 12:55 UTC, milespetrov approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-15 18:43 UTC, james-rae approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3939)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-15 18:43 UTC, merged