fix(legend): add tooltip and icon for Multipoint geometry
fgpv-vpgf/fgpv-vpgf pull request #3947
Opened 2021-06-21 18:40 UTC by RyanCoulsonCA

Closes #3945 

This PR adds an icon and tooltip to the legend when displaying a layer that uses multipoint geometry.

You can find a demo of this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-3945/samples/index-samples.html). Try to import the following feature layer using the wizard and check that the symbol shows up in the legend entry. When hovering over the symbol, the tooltip should say `ESRI Feature Layer (974 points)`.

The feature layer: https://maps-cartes.services.geo.ca/server_serveur/rest/services/IAAC/assessment_inventory_en/MapServer/0

2021-06-21 19:41 UTC, yileifeng approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-22 17:52 UTC, james-rae requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[packages/ramp-core/src/locales/translations.csv, line 273 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947#-McoqHnO5_smbMjiTmqV:-McoqHnP33nAmZIl6_Q-:b8qtmk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/128391e9c008c666abff08e849011ad5d77c250e/packages/ramp-core/src/locales/translations.csv#L273)):*
> ```CSV
> Geometry types,geometry.type.generic,feature|features,1,élément|éléments,1
> Geometry types,geometry.type.esriGeometryPoint,point|points,1,point|points,1
> Geometry types,geometry.type.esriGeometryMultipoint,point|points,1,point|points,1
> ```

I think we need to say multipoint(s). In your sample, we are saying 974 points, but on the map there are more than that, as some features have more than one point geometry.


<!-- Sent from Reviewable.io -->

2021-06-22 18:03 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @james-rae and @yileifeng)

___
*[packages/ramp-core/src/locales/translations.csv, line 273 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947#-McoqHnO5_smbMjiTmqV:-Mcorn3X2Pe-D_lD3L0q:b-rquxt2) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/128391e9c008c666abff08e849011ad5d77c250e/packages/ramp-core/src/locales/translations.csv#L273)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I think we need to say multipoint(s). In your sample, we are saying 974 points, but on the map there are more than that, as some features have more than one point geometry.
</blockquote></details>

Makes sense. Fixed.


<!-- Sent from Reviewable.io -->

2021-06-22 18:15 UTC, james-rae approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-22 20:18 UTC, elsa-huang approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-22 20:25 UTC, sharvenp approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2021-06-23 13:55 UTC, merged