fix(geo): use placeholder symbology in tables/details for arcade
fgpv-vpgf/fgpv-vpgf pull request #3951
Opened 2021-06-25 12:38 UTC by yileifeng

Closes #3925 

This may be a bit harder to test since there is inconsistency in that the layer will sometimes error out when loading. 
1. Add this layer containing arcade symbology https://gisp.dfo-mpo.gc.ca/arcgis/rest/services/FGP/PATH/MapServer/0 and wait for it to fully load (hopefully)
2. Opening up the details panel or data table should work with a placeholder `?` symbology icon

[Demo link](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3925-arcade-symbology/samples/index-samples.html)

2021-06-25 12:48 UTC, milespetrov approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-25 12:50 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-25 12:51 UTC, sharvenp approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-25 13:23 UTC, elsa-huang approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-25 15:35 UTC, james-rae approved these changes
What is the "inconsistency" with the layer?  Just server errors?

There are a couple of problems with the way this is implemented. Minor problem, the legend shows actual symbols, which conflicts with all the other views. Major problem, the checkbox filters on the legend symbols explode.

Suggest doing what the issue comment described and actually turn the renderer into a simple renderer, rather than intercepting search requests.

I'd think `cleanRenderer` function would be the easiest spot to do that. You'll move most of your current code block there, and just change the renderer properties to be the simple type right there. Then everything else will see a simple renderer going forward.  It will also be more efficient as you won't be generating `?` svg every time an icon is needed.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951#-:-Md2nGjO7dSnWBcRJg4y:b-jxi8q2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-28 13:59 UTC, yileifeng reviewed
Yep, I think it was mostly server errors. I reworked the implementation as suggested to move the code to `cleanRenderer`. Let me know if the new setup process requires any changes.  

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951#-:-MdHuKth5BFTCRItCzfV:bds0js4)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @elsa-huang, @milespetrov, @RyanCoulsonCA, and @sharvenp)



<!-- Sent from Reviewable.io -->

2021-06-28 14:01 UTC, spencerwahl approved these changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-28 14:22 UTC, sharvenp approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-28 15:13 UTC, james-rae requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[packages/ramp-geoapi/src/symbology.js, line 263 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951#-MdI2D6f2d1ntLy2BXX5:-MdI2D6f2d1ntLy2BXX6:b29n4s7) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d96a3c614f05b9993fb6d9c21a997c327198967f/packages/ramp-geoapi/src/symbology.js#L263)):*
> ```JavaScript
>             svgcode = renderer.svgcode;
>             // check for layer with arcade symbology converted to simple renderer
>             symbol = !renderer.valueExpression ? renderer.symbol : {};
> ```

do we need this change? You're setting the `renderer.symbol` in `cleanRenderer` so it should be defined even if there is a `valueExpression`

I can't test at the moment cuz the service is toast so maybe this code is obvious when I can run stuff...


<!-- Sent from Reviewable.io -->

2021-06-28 15:25 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

___
*[packages/ramp-geoapi/src/symbology.js, line 263 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951#-MdI2D6f2d1ntLy2BXX5:-MdIBv3u2kkTj1_OyjBO:b-ti6b98) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d96a3c614f05b9993fb6d9c21a997c327198967f/packages/ramp-geoapi/src/symbology.js#L263)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

do we need this change? You're setting the `renderer.symbol` in `cleanRenderer` so it should be defined even if there is a `valueExpression`

I can't test at the moment cuz the service is toast so maybe this code is obvious when I can run stuff...
</blockquote></details>

It was to prevent displaying the placeholder `?` symbols on the map when getting identify results. I thought it looked a bit strange, something like this: 

![image.PNG](https://files.reviewableusercontent.io/images/reviewable/31557789/QwqSijTtYiJ-ozbQM9qvcVZU/image.png)

So I chose to show no symbol instead, but I can adjust the dimensions of the symbol and use it if that's the preferred option.


<!-- Sent from Reviewable.io -->

2021-06-28 15:32 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)



<!-- Sent from Reviewable.io -->

2021-06-28 15:37 UTC, james-rae requested changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[packages/ramp-geoapi/src/symbology.js, line 263 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951#-MdI2D6f2d1ntLy2BXX5:-MdIFrX95xgbGXTOw6Uh:b-17bx6e) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/d96a3c614f05b9993fb6d9c21a997c327198967f/packages/ramp-geoapi/src/symbology.js#L263)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

It was to prevent displaying the placeholder `?` symbols on the map when getting identify results. I thought it looked a bit strange, something like this: 

![image.PNG](https://files.reviewableusercontent.io/images/reviewable/31557789/QwqSijTtYiJ-ozbQM9qvcVZU/image.png)

So I chose to show no symbol instead, but I can adjust the dimensions of the symbol and use it if that's the preferred option.
</blockquote></details>

ah ok that makes sense. The symbol result here is being used for highlighting. Maybe just expand the comment, saying something like "empty object for valueExpression avoids large question mark icon appearing during map highlighting."


<!-- Sent from Reviewable.io -->

2021-06-28 15:42 UTC, james-rae approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-28 15:54 UTC, spencerwahl approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-06-28 17:21 UTC, merged