WCAG - alert users on map changes
fgpv-vpgf/fgpv-vpgf pull request #3953
Opened 2021-07-02 14:07 UTC by yileifeng

Closes #3847

Announces map changes to screen reader users. Currently, the user is only alerted upon opening a data table (when it finishes loading) and when legend symbology is toggled as these were the two instances discussed in the issue. If there are more map changes that should be included (e.g. expanding details, opening settings/metadata panels, etc.), leave a comment and I will work on incorporating those in the PR.

Most of the browser extension SRs seemed to be fairly low quality so I ended up using [Microsoft Narrator](https://support.microsoft.com/en-us/windows/complete-guide-to-narrator-e4397a0d-ef4f-b386-d8ae-c172f109bdb1) for testing which I found to be quite good. Let me know if there is a default/recommended SR that should be used instead.

[Demo link](http://ramp4-app.azureedge.net/legacy/users/yileifeng/3847-WCAG-alert-changes/samples/index-samples.html)

Thanks to @RyanCoulsonCA for helping out and testing PR with SR

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)

2021-07-02 14:21 UTC, spencerwahl commented
> If there are more map changes that should be included (e.g. expanding details, opening settings/metadata panels, etc.)

The issue seems to want all dynamic updates to be announced, so definitely panels opening and expanding details. Probably also something for layers being added/deleted. I'm not sure what else would be useful.

2021-07-02 14:27 UTC, spencerwahl requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 3 unresolved discussions (waiting on @yileifeng)

___
*[packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js, line 434 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-Mdbb-ph-G0VbemP6Fy5:-Mdbb-ph-G0VbemP6Fy6:b-nik95k) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b02aa3b52c41937c60229104f1dc05964a92e63f/packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js#L434)):*
> ```JavaScript
>                 // alert user that symbology has been expanded/collapsed
>                 if (expandedChanged) {
>                     const alert = $('.rv-inner-shell').find('.rv-alert-message');
> ```

Are we ok with using jQuery? I can't remember what our last decision was.
___
*[packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js, line 438 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-Mdbb8lS1u8li5JUK04P:-Mdbb8lTE-KNbrLWvhXO:b-cuyhgz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b02aa3b52c41937c60229104f1dc05964a92e63f/packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js#L438)):*
> ```JavaScript
>                         ? $translate.instant('toc.layer.label.symbologyExpand')
>                         : $translate.instant('toc.layer.label.symbologyCollapse');
>                     const alertEl = $(`<span>${alertMsg}</span>`);
> ```

It might be easier (for adding more alerts) to make an api function that takes a string and then creates and inserts the element itself.
___
*[packages/ramp-core/src/content/styles/modules/_shell.scss, line 93 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-MdbbS42-voOX2FmHa-f:-MdbbS42-voOX2FmHa-g:b-kuvspd) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b02aa3b52c41937c60229104f1dc05964a92e63f/packages/ramp-core/src/content/styles/modules/_shell.scss#L93)):*
> ```SCSS
> 
>         // sr-only accessible hiding element (only accessible to screen reader users)
>         .rv-alert-message {
> ```

does `display: none;` make it not announce anything?


<!-- Sent from Reviewable.io -->

2021-07-02 14:31 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 3 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[packages/ramp-core/src/content/styles/modules/_shell.scss, line 93 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-MdbbS42-voOX2FmHa-f:-MdbcN5DD8P34QAmzl49:b-tz4i02) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b02aa3b52c41937c60229104f1dc05964a92e63f/packages/ramp-core/src/content/styles/modules/_shell.scss#L93)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

does `display: none;` make it not announce anything?
</blockquote></details>

Yep, I think using `display: none` makes the element inaccessible to screen readers


<!-- Sent from Reviewable.io -->

2021-07-05 13:49 UTC, james-rae approved these changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 2 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js, line 434 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-Mdbb-ph-G0VbemP6Fy5:-MdqvBJj3jmncjiOB5j5:b-htdyw4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b02aa3b52c41937c60229104f1dc05964a92e63f/packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js#L434)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

Are we ok with using jQuery? I can't remember what our last decision was.
</blockquote></details>

its used all over the focus manager and other spots. iirc it is some trick that uses whatever jquery is on the page. 


<!-- Sent from Reviewable.io -->

2021-07-05 18:28 UTC, yileifeng reviewed
Added alert announcements for the following (as of now): 
- data table loaded
- expanding/collapsing symbology
- opening/closing details panel
- expanding details panel
- expanding/collapsing identify entries in details
- opening settings panel
- opening metadata panel
- adding layer via wizard (user-added)
- removing layers from legend

I'm not sure what else needs to be added, so let me know if there are other important changes that should get announced. Still doing some testing with SR, it would probably be nice to get some QA testing for the PR.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-:-MdrudFs7WJTFfof1ii2:b-8hkwwy)* status: 2 of 13 files reviewed, 2 unresolved discussions (waiting on @james-rae and @spencerwahl)

___
*[packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js, line 438 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-Mdbb8lS1u8li5JUK04P:-Mdrv9AJ5YskL6AXAtK9:b174hmv) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b02aa3b52c41937c60229104f1dc05964a92e63f/packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js#L438)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

It might be easier (for adding more alerts) to make an api function that takes a string and then creates and inserts the element itself.
</blockquote></details>

Done, added this function in `shell.service` but can move to different file if there is better location


<!-- Sent from Reviewable.io -->

2021-07-05 19:20 UTC, james-rae approved these changes
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 2 unresolved discussions (waiting on @spencerwahl)



<!-- Sent from Reviewable.io -->

2021-07-05 19:27 UTC, RyanCoulsonCA requested changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 3 unresolved discussions (waiting on @spencerwahl and @yileifeng)

___
*[packages/ramp-core/src/app/core/shell.service.js, line 177 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-Mds7fXg8liz4Bl14VYC:-Mds7fXh55swgyot509K:b-olkcyt) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8085732c8e86ea589301ece3780b6a78b40cef70/packages/ramp-core/src/app/core/shell.service.js#L177)):*
> ```JavaScript
>      */
>     function updateAlert(alertMsg, params) {
>         console.log("alert message: ", alertMsg, params);
> ```

Probably want to remove the `console.log` here


<!-- Sent from Reviewable.io -->

2021-07-05 19:32 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @james-rae, @RyanCoulsonCA, and @spencerwahl)

___
*[packages/ramp-core/src/app/core/shell.service.js, line 177 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953#-Mds7fXg8liz4Bl14VYC:-Mds9-oh3H4lsy5DPgPm:bb6un1j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/8085732c8e86ea589301ece3780b6a78b40cef70/packages/ramp-core/src/app/core/shell.service.js#L177)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Probably want to remove the `console.log` here
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-07-05 19:32 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 7 files at r1, 9 of 11 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 2 unresolved discussions (waiting on @spencerwahl)



<!-- Sent from Reviewable.io -->

2021-07-05 20:16 UTC, james-rae approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 2 unresolved discussions (waiting on @spencerwahl)



<!-- Sent from Reviewable.io -->

2021-07-06 12:35 UTC, sharvenp approved these changes
> Reviewed 2 of 7 files at r1, 9 of 11 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: all files reviewed, 2 unresolved discussions (waiting on @spencerwahl)



<!-- Sent from Reviewable.io -->

2021-07-06 19:12 UTC, spencerwahl approved these changes
> Reviewed 9 of 11 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-07-06 19:31 UTC, james-rae approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/3953)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2021-07-06 19:31 UTC, merged