fix(details): add validate function to autolink function
fgpv-vpgf/fgpv-vpgf pull request #4008
Opened 2021-12-09 18:31 UTC by RyanCoulsonCA

Closes #4001 

This PR adds a validate function to the linkifyjs formatter to ensure that domain names are at least two characters long (as is required to be a valid domain name) in order to prevent it from converting `p.id` to a hyperlink.

You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-4001/samples/index-samples.html). I'm not able to load the service linked in the initial issue but just ensure that the details panel is still working as expected.

2021-12-10 15:19 UTC, james-rae requested changes
You can test with [this layer](https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/TC_Assessments_EN/MapServer/0), add via wizard as feature layer. The layer won't show on the map (data/renderer mismatch, service fault), but you can open the grid, apply filter on the `FILE NUMBER` column for `2021-204677`, hit the details button, and then see that it works by viewing the description field.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008#-:-MqZuJI69TTOmH9BgXhm:b7uxtxt)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[packages/ramp-core/src/app/core/formatters.filter.js, line 53 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008#-MqZus_fAetSbT77JVie:-MqZus_g6R2aaxCNLdcz:bofdzf9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b2fae06b1232cef4baa6d025f82d7b003fb42d4/packages/ramp-core/src/app/core/formatters.filter.js#L53)):*
> ```JavaScript
>         ignoreTags: ['script'],
>         validate: {
>             url: (value) => /^\w(\w+)/.test(value), // before converting to a link, ensure that the domain name is at least 2 characters long.
> ```

is the comment correct? if it is, do we want to change to use the validation that was decided yesterday here: https://github.com/ramp4-pcar4/ramp4-pcar4/issues/753#issuecomment-989945096


<!-- Sent from Reviewable.io -->

2021-12-13 14:10 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

___
*[packages/ramp-core/src/app/core/formatters.filter.js, line 53 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008#-MqZus_fAetSbT77JVie:-Mqo71QC4k2jZHgk8Zgf:b-h5m99q) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b2fae06b1232cef4baa6d025f82d7b003fb42d4/packages/ramp-core/src/app/core/formatters.filter.js#L53)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

is the comment correct? if it is, do we want to change to use the validation that was decided yesterday here: https://github.com/ramp4-pcar4/ramp4-pcar4/issues/753#issuecomment-989945096
</blockquote></details>

Yeah I wasn't sure if we wanted to do that for the RAMP3 issue or just for RAMP4. For now I do have it just looking for 2 or more characters, but I can change it to the `http/https` check if we want that for RAMP3 as well.


<!-- Sent from Reviewable.io -->

2021-12-13 14:13 UTC, james-rae commented
___
*[packages/ramp-core/src/app/core/formatters.filter.js, line 53 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008#-MqZus_fAetSbT77JVie:-Mqo856q-cnJryHdjXF7:b-p14sct) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b2fae06b1232cef4baa6d025f82d7b003fb42d4/packages/ramp-core/src/app/core/formatters.filter.js#L53)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Yeah lets do it and be safe. Will save us needing to do another patch release later to cover `respect.id`
</blockquote></details>

And then we can steal your fix for R4


<!-- Sent from Reviewable.io -->

2021-12-13 15:31 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008)* status: all files reviewed, 1 unresolved discussion (waiting on @james-rae)

___
*[packages/ramp-core/src/app/core/formatters.filter.js, line 53 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008#-MqZus_fAetSbT77JVie:-MqoPnNs92qXwo8ykwPv:bbo8jpn) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b2fae06b1232cef4baa6d025f82d7b003fb42d4/packages/ramp-core/src/app/core/formatters.filter.js#L53)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

And then we can steal your fix for R4
</blockquote></details>

This is done but it seems like services are down so I'm unable to test at the moment. Once they're back up I'll push the changes.


<!-- Sent from Reviewable.io -->

2021-12-14 15:33 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @james-rae)

___
*[packages/ramp-core/src/app/core/formatters.filter.js, line 53 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4008#-MqZus_fAetSbT77JVie:-MqtYPDuC3MFlIAOB305:b-lc7yeu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b2fae06b1232cef4baa6d025f82d7b003fb42d4/packages/ramp-core/src/app/core/formatters.filter.js#L53)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This is done but it seems like services are down so I'm unable to test at the moment. Once they're back up I'll push the changes.
</blockquote></details>

Should be good now! I was able to test locally by temporarily changing the HTML value of [this line](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/v3.3.4/packages/ramp-core/src/app/ui/details/details-record-esrifeature-item.html#L82). Everything seems to work as expected.


<!-- Sent from Reviewable.io -->

2021-12-14 18:03 UTC, merged