feat(toc): add focusable element to see full layer name
fgpv-vpgf/fgpv-vpgf pull request #4033
Opened 2022-08-17 14:49 UTC by RyanCoulsonCA

Closes #4022

This PR adds a new focusable element to the legend entries that have names that are too long to be displayed. 

Focusing on this new element will display the full name of the layer as a tooltip. This PR also makes it so a tooltip displaying the layer's name appears when hovering over entries that have a data grid (as it already does for legend groups).

--- 
This PR doesn't have to be the final version. If anyone has better ideas for displaying the full name of layers that are cut-off through keyboard navigation, or if you don't like the placement of the new element on the legend, I'm very much open to feedback.

You can find a demo for this PR [here](http://ramp4-app.azureedge.net/legacy/users/RyanCoulsonCA/fix-4022/samples/index-samples.html).

2022-08-17 18:09 UTC, yileifeng reviewed
Is there no good solution to make all layer containers focusable? That feels like the best solution just because the current focus behavior feels odd having some legend entries tabbable while others without datatable enabled cannot be tabbed. Also, hovering the layer for entries without datatable (e.g. "WMS Layer with ... long name") now properly displays the tooltip to the right, so we just have two tooltips showing the same information? 

If not possible, then maybe using the info icon as the focusable element would look a bit nicer for the current solution?

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033#-:-N9gU19m7ze_VYmc77lo:b69tkjn)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @james-rae)



<!-- Sent from Reviewable.io -->

2022-08-17 18:10 UTC, yileifeng reviewed
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)



<!-- Sent from Reviewable.io -->

2022-08-17 18:46 UTC, RyanCoulsonCA reviewed
I believe this was brought up in one of the meetings we had where we weren't sure about how making all containers focusable works from an accessibility standpoint. I do agree that making all layer containers focusable does seem like the nicest solution though, so if we conclude that accessibility isn't a problem we should go with that.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033#-:-N9h3-tf15OSGG7LJiM8:bpk3enw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @james-rae)



<!-- Sent from Reviewable.io -->

2022-08-17 19:14 UTC, james-rae approved these changes
I'd be tempted to see if we can get UX squad to look. Something to bring up next meeting.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033#-:-N9hDKoI73Rg_aEaal1P:b-dfk1hj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2022-08-19 13:47 UTC, RyanCoulsonCA commented
Quick update, I see that a class `rv-keyboard` gets added to the viewer when it's in keyboard mode, meaning that I could potentially add extra logic to the code to only display these new focusable buttons when we know the user is using a keyboard to navigate.

2022-09-20 20:30 UTC, spencerwahl requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`packages/ramp-core/src/app/ui/toc/templates/legend-error.html` line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033#-NCR_WloDfRhnXAaTuKE:-NCR_WloDfRhnXAaTuKF:bgpy2fu) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bda7acb785ca98be334f79d20920973e6f5eb651/packages/ramp-core/src/app/ui/toc/templates/legend-error.html#L30)):*
> ```HTML
> <div class="rv-list-item-controls">
>     <!-- if layer name is truncated, displays full layer name -->
>     <md-button ng-if="self.isNameTruncated" class="md-info-button rv-icon-14 rv-layer-item-flag">
> ```

Would it be possible to use something thats not a button? Might be a little confusing to screen readers. I forget how `md-tooltip` works but if it can be placed in a focusable div that probably makes the most sense.


<!-- Sent from Reviewable.io -->

2022-09-21 12:41 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[`packages/ramp-core/src/app/ui/toc/templates/legend-error.html` line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033#-NCR_WloDfRhnXAaTuKE:-NCV2HJrEWFjiVehjVCA:b6j4ln) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bda7acb785ca98be334f79d20920973e6f5eb651/packages/ramp-core/src/app/ui/toc/templates/legend-error.html#L30)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

Would it be possible to use something thats not a button? Might be a little confusing to screen readers. I forget how `md-tooltip` works but if it can be placed in a focusable div that probably makes the most sense.
</blockquote></details>

I agree, I was trying to do this before I resorted to using the button. For some reason adding `tabindex` to a div in the legend isn't making it focusable. I'm not sure if there's code somewhere that's making this happen, or if maybe I'm doing something wrong (changed `md-button` to a `div` and added `tabindex="0"`. Am I missing something?) 


<!-- Sent from Reviewable.io -->

2022-09-21 14:36 UTC, spencerwahl requested changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`packages/ramp-core/src/app/ui/toc/templates/legend-error.html` line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033#-NCR_WloDfRhnXAaTuKE:-NCVT7393QM0ecERf6gZ:b-o8fw83) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bda7acb785ca98be334f79d20920973e6f5eb651/packages/ramp-core/src/app/ui/toc/templates/legend-error.html#L30)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

I agree, I was trying to do this before I resorted to using the button. For some reason adding `tabindex` to a div in the legend isn't making it focusable. I'm not sure if there's code somewhere that's making this happen, or if maybe I'm doing something wrong (changed `md-button` to a `div` and added `tabindex="0"`. Am I missing something?) 
</blockquote></details>

In a normal situation that should work, I have a feeling focus manager is causing issues,

Maybe we can just set `role="presentation"` on the element.
Judging by the docs it should make it look like a div to screen readers; https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role


<!-- Sent from Reviewable.io -->

2022-09-21 14:52 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @james-rae, @spencerwahl, and @yileifeng)

___
*[`packages/ramp-core/src/app/ui/toc/templates/legend-error.html` line 30 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033#-NCR_WloDfRhnXAaTuKE:-NCVXGS19gkbWnP68M7N:b-5vi87j) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/bda7acb785ca98be334f79d20920973e6f5eb651/packages/ramp-core/src/app/ui/toc/templates/legend-error.html#L30)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

In a normal situation that should work, I have a feeling focus manager is causing issues,

Maybe we can just set `role="presentation"` on the element.
Judging by the docs it should make it look like a div to screen readers; https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role

</blockquote></details>

That sounds good to me, I've made the changes. An updated demo link can be found [here](https://fgpv-vpgf.github.io/fgpv-vpgf/fix-4022/samples/index-samples.html).


<!-- Sent from Reviewable.io -->

2022-09-21 15:27 UTC, spencerwahl approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2022-09-21 15:41 UTC, yileifeng approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2022-09-21 17:18 UTC, spencerwahl approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2022-09-22 14:04 UTC, james-rae approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2022-09-23 13:03 UTC, merged