Add support for geojson geometry collection
fgpv-vpgf/fgpv-vpgf pull request #4034
Opened 2022-08-26 14:41 UTC by yileifeng

Closes #4017 

Added support for GeoJSON with a geometry collection at geometry level by converting to a graphics record and creating a new `SimpleLayer`. Will not show up as legend block (correct behavior?) but individual geometries from the collection set are added to the layer/map. Only points and polygons are supported for now though, with the polygons being merged into one multi-polygon. 

**Testing**:
- add https://raw.githubusercontent.com/jolevesq/contributed-plugins/OSDP/osdp/src/samples/geoJSON/polygons.json as GeoJSON layer and ensure no errors
- all other layer behavior should remain unchanged 

[Demo](http://ramp4-app.azureedge.net/legacy/users/yileifeng/4017-geometry-collection/samples/index-samples.html)

2022-08-30 17:31 UTC, james-rae commented
Unfortunately it looks like any decision from the meetings wasn't recorded on the issue.
My memory says we wanted to run a filter & converter on the incoming GeoJSON. I.e. check that everything in the file was the same geometry type (so all point, all line, or all poly), then convert the content in-memory to a format that ramp could import.

This would allow it to appear in legend, have grid, identify, etc.

Notes from my markdown that I had shared with you earlier are in line with that.

- Write adapter to process any incoming GeoJSON
- Check for `GeometryCollection` as a geom `type`. Pass stuff through as is if not.
- Scan everything in the collections `geometries` array. Make sure the `type` is homogenous across the array
- If not homogenous, throw an error.
- If homogenous, convert to geom type & structure we support. Lines to `MultiLineString`, Points to `MultiPoint`, Polygons to `MultiPolygon`
- If the "collection" only had one, we could map to the non-Multi variants.
- Also need to check across the entire GeoJSON file, to ensure that everything is same type of geometry. Error if not. This check might already exist?

Might want to ping Dan and have a double-check with our NrCan friends before you make the change?





<!-- Sent from Reviewable.io -->

2022-08-30 18:28 UTC, jolevesq commented
@james-rae I think your solution is good. The import needs to act like a layer (legend, details and grids). Do you have some sample  JSON to test with? If not, I can ask some for you to test.

2022-08-30 18:31 UTC, james-rae commented
Great. 
It's a text file so I believe we can create some generic files that prove things work. Will just edit some standard geoJSON to have the GeometryCollection format.

If your client has more samples they would use, that would be helpful in making sure what we deliver will meet their expectations. So we won't say no to extra samples.





<!-- Sent from Reviewable.io -->

2022-09-01 17:33 UTC, yileifeng reviewed
Made changes with updated [Demo](https://fgpv-vpgf.github.io/fgpv-vpgf/4017-geometry-collection/samples/index-samples.html). EDIT: testing sample files provided

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-:-NAu6Mqz0-eBOYOXO-KA:b-aahic0)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-01 20:16 UTC, james-rae requested changes
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @james-rae and @yileifeng)

___
*[`packages/ramp-geoapi/src/layer.js` line 513 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NAuDVjIAp74r96Ul6--:-NAuDVjIAp74r96Ul6-0:b6gufmx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b77752287313b9eecc80e6a83c34bb762952859f/packages/ramp-geoapi/src/layer.js#L513)):*
> ```JavaScript
>     }
> 
>     let geomType = geoJson.features[0].geometry.type;
> ```

should be scanning every feature, not just the first one. The sample's we're given only have one item but that does not mean there is only one.
___
*[`packages/ramp-geoapi/src/layer.js` line 947 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NAuDipmD2H51hQGno2b:-NAuDipmD2H51hQGno2c:b-tqsnyk) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b77752287313b9eecc80e6a83c34bb762952859f/packages/ramp-geoapi/src/layer.js#L947)):*
> ```JavaScript
>  */
> function cleanUpGeomCollection(geoJson) {
>     const geoms = geoJson.features[0].geometry.geometries;
> ```

same, needs entire array processed.
___
*[`packages/ramp-geoapi/src/layer.js` line 964 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NAuECeJ7grfMUruUWh2:-NAuECeJ7grfMUruUWh3:b3lrbj1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b77752287313b9eecc80e6a83c34bb762952859f/packages/ramp-geoapi/src/layer.js#L964)):*
> ```JavaScript
>     } else {
>         // merge coordinates to form a multi-geometry structure
>         let combined = [];
> ```

can one-shot this pretty easy

`const combined = geoms.map(g => g.coordinates)`


<!-- Sent from Reviewable.io -->

2022-09-15 13:25 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @james-rae)

___
*[`packages/ramp-geoapi/src/layer.js` line 513 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NAuDVjIAp74r96Ul6--:-NC0Ji_Y3KlMs5Z_KBeG:b-3ad5ws) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b77752287313b9eecc80e6a83c34bb762952859f/packages/ramp-geoapi/src/layer.js#L513)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

should be scanning every feature, not just the first one. The sample's we're given only have one item but that does not mean there is only one.
</blockquote></details>

added scanning across entire file
___
*[`packages/ramp-geoapi/src/layer.js` line 947 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NAuDipmD2H51hQGno2b:-NC0JYtHCnlxr1eFpO5J:b-6afffx) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b77752287313b9eecc80e6a83c34bb762952859f/packages/ramp-geoapi/src/layer.js#L947)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

same, needs entire array processed.
</blockquote></details>

now only called when converting individual feature geometry collection type with `idx`
___
*[`packages/ramp-geoapi/src/layer.js` line 964 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NAuECeJ7grfMUruUWh2:-NC0JW07CZ6rkzHzW5rI:bah2568) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/b77752287313b9eecc80e6a83c34bb762952859f/packages/ramp-geoapi/src/layer.js#L964)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

can one-shot this pretty easy

`const combined = geoms.map(g => g.coordinates)`
</blockquote></details>

Donethanks


<!-- Sent from Reviewable.io -->

2022-09-15 13:49 UTC, james-rae requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`packages/ramp-geoapi/src/layer.js` line 544 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NC0MWHW43DY5xO75foK:-NC0MWHX64s8CxxyyIAe:b-eud74a) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6098fcd70248403830719faa2b6988554ab227ad/packages/ramp-geoapi/src/layer.js#L544)):*
> ```JavaScript
>         }
>     });
> ```

looks like you have a edge case fail with this logic. It's due to you sharing the `geomType` var both inside the GeometryCollection check, and outside at the feature level check.

Sample: Two feature file. First feature is normal feature, being a Point; Second feature is GeometryCollection, having Polygons

- `geomType = point`, set before the main loop
- loop processes first feature. Skips both `if` checks since `point === point`.
- Feature one ALL GOOD.
- loop processes second feature.
- goes into first `if` since Geom Collection
- overwrites `geomType` with first item in collection. Which is polygon.
- the inner `forEach` passes since the collection is all polygons.
- Feature two ALL GOOD.
- You've now given a gold star to a mismatch.

I'll leave it up to you how to restructure but you probably need to track a file level geometry type separately. Your inner GeomCollection loop should check all the same (as it does now), but then should also check against the file level geometry. Bit of a pain to file level the first time; sort of need to duplicate the checking logic. Or maybe you have better path.


<!-- Sent from Reviewable.io -->

2022-09-15 13:52 UTC, james-rae commented
*[`packages/ramp-geoapi/src/layer.js` line 544 at r3](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034#-NC0MWHW43DY5xO75foK:-NC0Po7nBZO48uR2PpU2:b-5l8dfc) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/6098fcd70248403830719faa2b6988554ab227ad/packages/ramp-geoapi/src/layer.js#L544)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

looks like you have a edge case fail with this logic. It's due to you sharing the `geomType` var both inside the GeometryCollection check, and outside at the feature level check.

Sample: Two feature file. First feature is normal feature, being a Point; Second feature is GeometryCollection, having Polygons

- `geomType = point`, set before the main loop
- loop processes first feature. Skips both `if` checks since `point === point`.
- Feature one ALL GOOD.
- loop processes second feature.
- goes into first `if` since Geom Collection
- overwrites `geomType` with first item in collection. Which is polygon.
- the inner `forEach` passes since the collection is all polygons.
- Feature two ALL GOOD.
- You've now given a gold star to a mismatch.

I'll leave it up to you how to restructure but you probably need to track a file level geometry type separately. Your inner GeomCollection loop should check all the same (as it does now), but then should also check against the file level geometry. Bit of a pain to file level the first time; sort of need to duplicate the checking logic. Or maybe you have better path.
</blockquote></details>

Ahhh my bad I missed a line
` if (geomType !== geoms[0].type && idx > 0) {`

Resolved


<!-- Sent from Reviewable.io -->

2022-09-15 15:53 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 4 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4034)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2022-09-15 18:42 UTC, merged