[In Progress, feedback needed] #4020 work
fgpv-vpgf/fgpv-vpgf pull request #4039
Opened 2022-09-15 15:46 UTC by RyanCoulsonCA

### ** Not for merging **

I'm a bit stuck on this issue so I'm publishing this PR with my current progress to ask for some suggestions or feedback on what I've got so far. Ignore all of the `console.log` lines, they're just there for me to remember where things are for now.

---

As far as I can tell, we're not currently getting any visibility stuff from the server side, and instead we just take it from the config file or default it if nothing exists in the config.

My implementation plan for this task is something along the lines of the this:
- when the layer loads, check whether it has it's visibility is set in the configuration file
- if the visibility is not set in the config and the layer has a `defaultVisibility` property from the server, then the layer visibility is set to the value of `defaultVisibility`

This implementation works for feature layers, and you can see the code for this in `layerRecord.js`.

**Question 1:** Is this a good implementation strategy? It seems to me like it should work, but am I missing any edge cases where this may not work?
**Question 2:** is the code for this in the right spot, or is there a better place for this? I figured this would be the spot since it's the same place we set the extent from the server if it's not defined in the config.

Next up, I'm running into issues getting this to work at all for dynamic layers. I tried running similar code for each leaf layer in the dynamicRecord.js file, but updating the visibility of the layer isn't working properly (I assume this is because the layer hasn't finished loading yet, so the `setVisibility` function isn't properly setting values). 

**Question 3**: similar to question 2, is this code for dynamic layers in the right spot? Again, this is where we set the extent if it's not defined in the config which is why I assume it should go here. If it is in the right spot, is there a way for me to confirm the layer has loaded before calling the `setVisibility` function to get this to work?

Any help at all would be greatly appreciated, my brain is 🤯 after being stuck on this for a while lol.

2022-09-15 17:34 UTC, james-rae commented
From the issue analysis HackMD

- Remove config defaulting for layer properties, probably `visiblity` and `opaciy`. Allow `undefined` to be a config value post-parsing
- In layer load functions, need to recognize the `undefined` value. Set some internal flag or whatnot.
- After layer metadata loads, check the flag. If set, grab server setting result and apply to layer.
- Will need to handle children of Dynamics as well as just root level layers.
- Skip for File, WFS, WMS(?)

Was any of this considered?





<!-- Sent from Reviewable.io -->

2022-09-15 17:35 UTC, james-rae commented
Because as is, appears to me the original problem persists: The config defaults all the booleans prior to load, so you never know if the user did or didn't provide a value





<!-- Sent from Reviewable.io -->

2022-09-15 17:37 UTC, james-rae commented
Or is `config.source` like an untouched/undefaulted copy?





<!-- Sent from Reviewable.io -->

2022-09-15 17:46 UTC, james-rae commented
*[`packages/ramp-geoapi/src/layer/layerRec/attribFC.js` line 72 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NC1FGTH75_-8e5bk96J:-NC1FGTH75_-8e5bk96K:b9sw06f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f9e2d5dca9b2dc35a06487cad20f7af01ce10a2/packages/ramp-geoapi/src/layer/layerRec/attribFC.js#L72)):*
> ```JavaScript
>                   return data.defaultVisibility;
>               })
>             : true;
> ```

you prob want `Promise.resolve(true)`; right now this getter is returning Promise or boolean depending on state; might be some of your problems is because you're doing `true.then()` in reality.


<!-- Sent from Reviewable.io -->

2022-09-15 17:53 UTC, james-rae commented
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 389 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NC1Gkd22bkCVWNZv0wy:-NC1Gkd22bkCVWNZv0wz:b-vmfq37) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f9e2d5dca9b2dc35a06487cad20f7af01ce10a2/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L389)):*
> ```JavaScript
>                     dFC.defaultVisibility.then((data) => {
>                         if (!hasVisibleState && data !== undefined) {
>                             // This isn't working, probably not finished loading
> ```

your prob right about the loading, i'mma look into the code guts.  But at a glance your line below could just be `dFC.setVisibility(data)`


<!-- Sent from Reviewable.io -->

2022-09-15 18:06 UTC, james-rae commented
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 428 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NC1I_Dt3G0qhiI-LwPj:-NC1I_Dt3G0qhiI-LwPk:b-gibpc1) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f9e2d5dca9b2dc35a06487cad20f7af01ce10a2/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L428)):*
> ```JavaScript
>         });
> 
>         // TODO careful now, as the dynamicFC.DynamicFC constructor also appears to be setting visibility on the parent.
> ```

I think this block is where you need additional sauce.
We're using [this badboy](https://developers.arcgis.com/javascript/3/jsapi/arcgisdynamicmapservicelayer-amd.html#setvisiblelayers) to set the initial sublayer visibilities. Right now this code is synchronous; which was fine before since all our visible bools were known from the config. But now you have checkers above that are getting set AFTER the server spits back info about each child layer; so it happens after this code has already run.

Off the cuff idea.
This whole `if/else` gets put behind `const coulsonPromise = Promise.all(loadPromises).then(this code)`
Then you need to add `coulsonPromise` to the final `Promise.all([loadPromises, coulsonPromise])` at the bottom, to ensure the layer doesn't go to loaded until this `if/else` finishes.

Secondly, make a temporary data structure in this meatball of a function (`onLoad`) to track the boolean states of visibility. You can initialize that structure with some of the guts below (that just checks configuration as is); but then you will be updating this structure with your findings above, where you're calling `defaultVisibility()` and such.

Then it's your new structure that is used to figure out what gets passed to `_layer.setVisibility()` below.


<!-- Sent from Reviewable.io -->

2022-09-15 18:11 UTC, james-rae commented
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 428 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NC1I_Dt3G0qhiI-LwPj:-NC1K60Q26yoqNkWlh2m:b-m8c4ao) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f9e2d5dca9b2dc35a06487cad20f7af01ce10a2/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L428)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I think this block is where you need additional sauce.
We're using [this badboy](https://developers.arcgis.com/javascript/3/jsapi/arcgisdynamicmapservicelayer-amd.html#setvisiblelayers) to set the initial sublayer visibilities. Right now this code is synchronous; which was fine before since all our visible bools were known from the config. But now you have checkers above that are getting set AFTER the server spits back info about each child layer; so it happens after this code has already run.

Off the cuff idea.
This whole `if/else` gets put behind `const coulsonPromise = Promise.all(loadPromises).then(this code)`
Then you need to add `coulsonPromise` to the final `Promise.all([loadPromises, coulsonPromise])` at the bottom, to ensure the layer doesn't go to loaded until this `if/else` finishes.

Secondly, make a temporary data structure in this meatball of a function (`onLoad`) to track the boolean states of visibility. You can initialize that structure with some of the guts below (that just checks configuration as is); but then you will be updating this structure with your findings above, where you're calling `defaultVisibility()` and such.

Then it's your new structure that is used to figure out what gets passed to `_layer.setVisibility()` below.

</blockquote></details>

So in a nutshell, the flow is

1. Create an appropriate visibility tracking structure (index mapped to boolean?).
2. Init it BEFORE the `update async values` loop above. The init code is what we see below, checking `config.state.visibility` and such.
3. Then the async values code comes; almost as you have it now, but instead of setting visiblity on `dFC.setVisibility()`, you are updating your new structure.
4. The calls to `_layer.` in the `if/else` below then sit behind a promise.all that is waiting for all the other stuff (mainly the FC async calls, which are inspecting server visibility). 
5. Once that promise all resolves, we use your fancy structure to feed into the layer visibility initiation methods.  That code then resolves and our layer flips to loaded


<!-- Sent from Reviewable.io -->

2022-09-15 18:32 UTC, RyanCoulsonCA reviewed
> Or is config.source like an untouched/undefaulted copy?

Yeah, as far as I can tell `config.source` is basically an un-defaulted copy, at least for feature layers. Dynamic layer leaf nodes don't seem to have this.

> From the issue analysis HackMD

Totally forgot there was a HackMD, my bad. It seems like because config.source is an unmodified version of the properties my code sort of does the same thing anyway. I will look into removing the defaults though, since it doesn't seem like dynamic leaf nodes have this property.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-:-NC1O4h-Bez7cwHqQDzg:b-k7u56w)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @james-rae, @RyanCoulsonCA, and @yileifeng)

___
*[`packages/ramp-geoapi/src/layer/layerRec/attribFC.js` line 72 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NC1FGTH75_-8e5bk96J:-NC1Q9XJ2y_myeWNu-51:b-vlm2yz) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f9e2d5dca9b2dc35a06487cad20f7af01ce10a2/packages/ramp-geoapi/src/layer/layerRec/attribFC.js#L72)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

you prob want `Promise.resolve(true)`; right now this getter is returning Promise or boolean depending on state; might be some of your problems is because you're doing `true.then()` in reality.
</blockquote></details>

Good catch :thumbsup: 
___
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 428 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NC1I_Dt3G0qhiI-LwPj:-NC1Pglw9XimpKkdUJsf:b-fy0w78) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5f9e2d5dca9b2dc35a06487cad20f7af01ce10a2/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L428)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

So in a nutshell, the flow is

1. Create an appropriate visibility tracking structure (index mapped to boolean?).
2. Init it BEFORE the `update async values` loop above. The init code is what we see below, checking `config.state.visibility` and such.
3. Then the async values code comes; almost as you have it now, but instead of setting visiblity on `dFC.setVisibility()`, you are updating your new structure.
4. The calls to `_layer.` in the `if/else` below then sit behind a promise.all that is waiting for all the other stuff (mainly the FC async calls, which are inspecting server visibility). 
5. Once that promise all resolves, we use your fancy structure to feed into the layer visibility initiation methods.  That code then resolves and our layer flips to loaded

</blockquote></details>

This is super helpful, thanks. I'm going to play around and see if I can get it working.


<!-- Sent from Reviewable.io -->

2022-09-15 18:36 UTC, james-rae commented
> since it doesn't seem like dynamic leaf nodes have this property

You'd probably need to use the parent layers `config.source.layerEntries[index].state.visibility` lol. I'm ok with the `.source` approach; this codebase is at a "patch only" phase of life so uber-elegance isn't required unless we need to. Your call.





<!-- Sent from Reviewable.io -->

2022-09-15 18:39 UTC, james-rae commented
^ a bit wrong
`config.source.layerEntries.find(le => le.index === targetIndex).state.visibility`, with maybe extra code incase the `.find` returns nothing.





<!-- Sent from Reviewable.io -->

2022-09-20 19:15 UTC, RyanCoulsonCA commented
I've made a bunch of changes to the PR and it works for both feature layers and dynamic layers now. Everything else seems to work the way it used to, but please look it over when you have time to make sure nothing has broken!

2022-09-20 20:25 UTC, spencerwahl approved these changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039)* status: all files reviewed, 3 unresolved discussions (waiting on @james-rae, @RyanCoulsonCA, and @yileifeng)



<!-- Sent from Reviewable.io -->

2022-09-21 14:56 UTC, james-rae requested changes
> Reviewed 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039)* status: all files reviewed, 5 unresolved discussions (waiting on @james-rae, @RyanCoulsonCA, and @yileifeng)

___
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 472 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NCVUcvi9Bh0FqpxK-Iz:-NCVUcvi9Bh0FqpxK-J-:b23mqhj) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2390336dd87f8eeff39a6f9025d205ba177400a0/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L472)):*
> ```JavaScript
>                     this.name = serviceResult.mapName;
>                 });
>                 loadPromises.push(setTitle);
> ```

mild concern with this. The Promise.all below is inspecting the `loadPromises` array. That `.all` call happens before this runs.  I don't know if you push a promise to the array after the fact, if the `.all` will consider it.
I'd say either remove this `if` from inside the `loadLayerPromise` guts (so the push just happens in the main function, and before the final Promise.all,  or you need to wire in the `setTitle` promise to act as a resolver to `loadLayerPromise`, which is probably more work.
___
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 476 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NCVVcrb488QFgfb_bUr:-NCVVcrb488QFgfb_bUs:beg24al) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2390336dd87f8eeff39a6f9025d205ba177400a0/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L476)):*
> ```JavaScript
>         });
> 
>         Promise.all([loadLayerPromise, loadPromises]).then(() => {
> ```

`loadPromises` is an array. so you're parameter is `[promise, [promise, promise, promise, ...]]`

You might want to do something like `loadPromises.concat([loadLayerPromise])`, or `[loadLayerPromise, ...loadPromises]`.

A `.push()` might work, but then your pushing `loadLayerPromise` into the array that `loadLayerPromise` is `.all`ing on which might create a black hole or something.
___
*[`packages/ramp-geoapi/src/layer/layerRec/layerRecord.js` line 300 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NCVXbY6-f8lCf30w44C:-NCVXbY6-f8lCf30w44D:b-x8nkad) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2390336dd87f8eeff39a6f9025d205ba177400a0/packages/ramp-geoapi/src/layer/layerRec/layerRecord.js#L300)):*
> ```JavaScript
> 
>         this.extent = shared.makeSafeExtent(this.extent);
>         this.defaultVisibility = this._layer.defaultVisibility;
> ```

this is becoming a layer property. I don't see it being read anywhere other than this function. It also has same name as the FC property but different data type (boolean vs Promise(boolean)).

If we don't need it outside of here, can this just be a `const`?
If we do need it persisted, can we add a comment about its type and whatnot. Without typescript this will get confusing.


<!-- Sent from Reviewable.io -->

2022-09-21 15:21 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @james-rae, @RyanCoulsonCA, @spencerwahl, and @yileifeng)

___
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 472 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NCVUcvi9Bh0FqpxK-Iz:-NCVbZU68seRgrK1q9ie:b-zcyad4) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2390336dd87f8eeff39a6f9025d205ba177400a0/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L472)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

mild concern with this. The Promise.all below is inspecting the `loadPromises` array. That `.all` call happens before this runs.  I don't know if you push a promise to the array after the fact, if the `.all` will consider it.
I'd say either remove this `if` from inside the `loadLayerPromise` guts (so the push just happens in the main function, and before the final Promise.all,  or you need to wire in the `setTitle` promise to act as a resolver to `loadLayerPromise`, which is probably more work.
</blockquote></details>

You're right, didn't catch that. I've moved it outside of the loadLayerPromise.
___
*[`packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js` line 476 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NCVVcrb488QFgfb_bUr:-NCVbea30Zky_SRFXcOK:bt2vr0y) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2390336dd87f8eeff39a6f9025d205ba177400a0/packages/ramp-geoapi/src/layer/layerRec/dynamicRecord.js#L476)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

`loadPromises` is an array. so you're parameter is `[promise, [promise, promise, promise, ...]]`

You might want to do something like `loadPromises.concat([loadLayerPromise])`, or `[loadLayerPromise, ...loadPromises]`.

A `.push()` might work, but then your pushing `loadLayerPromise` into the array that `loadLayerPromise` is `.all`ing on which might create a black hole or something.
</blockquote></details>

Fixed!
___
*[`packages/ramp-geoapi/src/layer/layerRec/layerRecord.js` line 300 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039#-NCVXbY6-f8lCf30w44C:-NCVbfGI-i_S-XdbylpW:b-28bwbm) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/2390336dd87f8eeff39a6f9025d205ba177400a0/packages/ramp-geoapi/src/layer/layerRec/layerRecord.js#L300)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this is becoming a layer property. I don't see it being read anywhere other than this function. It also has same name as the FC property but different data type (boolean vs Promise(boolean)).

If we don't need it outside of here, can this just be a `const`?
If we do need it persisted, can we add a comment about its type and whatnot. Without typescript this will get confusing.
</blockquote></details>

It definitely doesn't need to be a layer property. I've changed it to be a const.


<!-- Sent from Reviewable.io -->

2022-09-21 15:59 UTC, yileifeng approved these changes
> Reviewed 2 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2022-09-23 13:00 UTC, spencerwahl approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2022-09-23 13:22 UTC, merged