Fix opening side menu on multiple instances
fgpv-vpgf/fgpv-vpgf pull request #4045
Opened 2022-09-26 18:55 UTC by yileifeng

Closes https://github.com/ramp4-pcar4/story-ramp/issues/202

Fixes Storylines issue where page jumps to a previous map (with side menu already open) after opening side menu for a different map on the page. This is due to sidemenu IDs named the same so we end up calling `rvFocus` on the first element found. Instead, using `$rootElement.find()` should find the correct menu. Changes to sample page can be discarded after demo if needed.

2022-09-27 14:19 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2022-09-27 17:24 UTC, spencerwahl requested changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`packages/ramp-core/src/app/ui/sidenav/sidenav.service.js` line 325 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045#-NCzyUVM45caLRfXvxNp:-NCzyUVM45caLRfXvxNq:b-rzum2v) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b6b9bac4c68e7c656251dd20d153956e4a68a61/packages/ramp-core/src/app/ui/sidenav/sidenav.service.js#L325)):*
> ```JavaScript
>         $mdSidenav('left')
>             .open()
>             .then(() => $rootElement.find('md-sidenav[md-component-id="left"] button').first().rvFocus());
> ```

does the sidenav need an ID? Duplicate ids can mess with screenreaders so if we can avoid that we should.


<!-- Sent from Reviewable.io -->

2022-09-27 19:03 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @spencerwahl)

___
*[`packages/ramp-core/src/app/ui/sidenav/sidenav.service.js` line 325 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045#-NCzyUVM45caLRfXvxNp:-ND-K8FWC7KiKElFXVL7:bofmq9s) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b6b9bac4c68e7c656251dd20d153956e4a68a61/packages/ramp-core/src/app/ui/sidenav/sidenav.service.js#L325)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

does the sidenav need an ID? Duplicate ids can mess with screenreaders so if we can avoid that we should.
</blockquote></details>

changed `md-component-id` to append `-{map ID}`, let me know if this works


<!-- Sent from Reviewable.io -->

2022-09-27 19:05 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @spencerwahl)

___
*[`packages/ramp-core/src/app/ui/sidenav/sidenav.service.js` line 325 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045#-NCzyUVM45caLRfXvxNp:-ND-KPJQEcea0JKIVW0O:b3h0ai9) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b6b9bac4c68e7c656251dd20d153956e4a68a61/packages/ramp-core/src/app/ui/sidenav/sidenav.service.js#L325)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

changed `md-component-id` to append `-{map ID}`, let me know if this works
</blockquote></details>

if so, can also update the other sidenav ID naming for basemaps (it is also just labeled `right` currently)


<!-- Sent from Reviewable.io -->

2022-09-27 19:22 UTC, spencerwahl approved these changes
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA, @spencerwahl, and @yileifeng)

___
*[`packages/ramp-core/src/app/ui/sidenav/sidenav.service.js` line 325 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045#-NCzyUVM45caLRfXvxNp:-ND-O9kJ2TzpQEHmogje:b-chn36o) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/5b6b9bac4c68e7c656251dd20d153956e4a68a61/packages/ramp-core/src/app/ui/sidenav/sidenav.service.js#L325)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

if so, can also update the other sidenav ID naming for basemaps (it is also just labeled `right` currently)
</blockquote></details>

Turns out I misunderstood what kind of id this is and its actually just set as `md-component-id` which shouldn't cause any issues... my bad for not investigating further.

Can leave these changes in or revert, up to you.


<!-- Sent from Reviewable.io -->

2022-09-28 18:12 UTC, james-rae approved these changes
> Reviewed 1 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4045)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2022-10-05 13:48 UTC, merged