fix(layer): storylines fix for filter query visibility
fgpv-vpgf/fgpv-vpgf pull request #4128
Opened 2023-07-08 19:56 UTC by JahidAhmed

fix for storylines issue where initial filter query was not being respected on visibility change

problem was in the code we have `change all symbology stack to toggled/untoggled if top layer is visible/invisible`, and technically if we disable individual toggling of symbology (which is a config option i set to false in sample 95), then it shouldn't be messing with the individual symbology visibilities at all.

now, since that portion is irrelevant in this case, we want to disable that block of code from executing. 

i also modified some of the table stuff to show only the relevant entries (especially on visibility change if table remains open), but that part is a bit confusing and im not sure if im breaking other edge cases.

2023-07-08 20:10 UTC, JahidAhmed commented
https://fgpv-vpgf.github.io/fgpv-vpgf/4066-initial-layer-query/samples/index-samples.html?sample=95

2023-07-08 20:27 UTC, yileifeng reviewed
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @james-rae)



<!-- Sent from Reviewable.io -->

2023-07-10 16:07 UTC, JahidAhmed reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @james-rae)

___
*[`packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js` line 173 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128#-N_-9vjk87CttjKkRSFp:-N_-Ye0aACkf6iFC494-:b-4wecl) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/21a4567c9bc77df1d82ff2f66097b4ee29f3d482/packages/ramp-core/src/app/ui/toc/symbology-stack.directive.js#L173)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lets add an extra comment line for the new condition. it's a bit obvious, but this code is some of the most obtuse in the app so really helps if comments tell the whole story.
</blockquote></details>

added some comments
___
*[`packages/ramp-core/src/content/samples/config/config-sample-95.json` line 286 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128#-N_-AW2j4Hr0qeksZCh4:-N_-Yasj6xZCuzTXSuow:boywt0f) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/21a4567c9bc77df1d82ff2f66097b4ee29f3d482/packages/ramp-core/src/content/samples/config/config-sample-95.json#L286)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

mildly curious why we're not using `=`, purely for performance over `IN`.
</blockquote></details>

not too sure why. copied over from storylines config
___
*[`packages/ramp-plugin-enhanced-table/src/panel-manager.ts` line 205 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128#-N_-B-fzB_7lUNMUwvva:-N_-Y_1Z36IkE79WQUwX:b-hfpv0l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/21a4567c9bc77df1d82ff2f66097b4ee29f3d482/packages/ramp-plugin-enhanced-table/src/panel-manager.ts#L205)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this part seems pretty dangerous. It will work with the specific example we're testing against, but makes the assumption that ANY initial filter is a replacement for the symbol filters, which isn't true.
Basically any RAMP site with an initial filter defined will end up with the grid ignoring any symbol filtering.
As an example, take our current data set, but initial filter is to restrict to a province and show all the animals. As you toggle animals, the grid will continue to show everything in the province, since that's the query you overwrite here.
Also a possibility the UI becomes out of synch...but probably not; I believe the symbol checkboxes only write to the SYMBOL filter, they don't read from it. 
</blockquote></details>

removed
___
*[`packages/ramp-plugin-enhanced-table/src/panel-rows-manager.ts` line 35 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128#-N_-Cp7N9yilZdbT9EqM:-N_-YYvQ84fMOyY4wPRN:b-hfpv0l) ([raw file](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/21a4567c9bc77df1d82ff2f66097b4ee29f3d482/packages/ramp-plugin-enhanced-table/src/panel-rows-manager.ts#L35)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

same assumption here. 
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2023-07-10 17:07 UTC, james-rae requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @JahidAhmed)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128#-N_-lDgt3iHL9tjS5xnQ):*
squash these two. PM me if you need the steps I have a cheat sheet


<!-- Sent from Reviewable.io -->

2023-07-10 17:38 UTC, JahidAhmed reviewed
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @james-rae)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128#-N_-lDgt3iHL9tjS5xnQ):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

squash these two. PM me if you need the steps I have a cheat sheet
</blockquote></details>

donethanks


<!-- Sent from Reviewable.io -->

2023-07-10 17:50 UTC, james-rae approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)



<!-- Sent from Reviewable.io -->

2023-07-10 17:51 UTC, yileifeng approved these changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpv-vpgf/4128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JahidAhmed)



<!-- Sent from Reviewable.io -->

2023-07-10 17:52 UTC, merged